### ISSUE TITLE
Remaining issues with indent script

### ISSUE THREAD

**Issue by pdesaulniers** [teal-language/vim-teal#10]
1. In tl.tl, there's a line that says
```lua
local standard_library: {string:Type} = {
```

The code that follows this huge table assignment (`for _, t in pairs(standard_library) do`, etc) is indented too far to the right.

I think this is because there's a variable name FUNCTION which increases the indentation. Here's a reduced test case:
```lua
local x = {
   y = FUNCTION,
      z = "hello"
   }
```

2. It seems like multiline `if` statements with parentheses are not getting indented:
```lua
if true then
   if (
      true or false
   ) then
   print("hello")
end
end
```

**Comment by pdesaulniers** [comment]
@euclidianAce Do you think it would be overkill to setup some unit tests for the indent script (and maybe the syntax file)? Do you know if there are some other Vim plugins that do this?

**Comment by euclidianAce** [comment]
I was just about to open another issue outlining some of the problems with tl.tl, I add it as a comment onto this issue later.

> I think this is because there's a variable name FUNCTION which causes indentation

I thought I squashed this one, but I think there is some `set ignorecase` shenanigans or something going on here
> It seems like multiline if statements with parentheses are not getting indented:

This one is probably an easy fix, (hopefully).

> Do you think it would be overkill to setup some unit tests for the indent script (and maybe the syntax file)?

I think that would be great but I really don't know of any frameworks or anything, especially for vimscript, and especially for an indent function, but I'll look around as my current testing/debugging workflow is putting a bunch of `echoerr` in the indent function and doing `:debug call GetTealIndent()` to actually read the error output.

**Comment by pdesaulniers** [comment]
> I thought I squashed this one, but I think there is some set ignorecase shenanigans or something going on here

Ahh, I think you're right! I've removed `set ignorecase` from my .vimrc, and the indentation now looks as expected.

**Comment by euclidianAce** [comment]
An outline on some of the errors:
(Specifically on tl.tl, commit f4ff7af, a roughly 6500 line file):

Using `gg=G` to format the entire file is fine for the first thousand lines, but then on line 1180:
```
local function parse_function_type(ps: ParseState, i: number): number, Type
	local node = new_type(ps, i, "function")
		node.args = {}
		node.rets = {}
```
The `"function"` caused an indent for some reason. Hitting `=G` again fixes it.

Line 1322, same problem:
```
local function parse_function_value(ps: ParseState, i: number): number, Node
	local node = new_node(ps.tokens, i, "function")
		i = verify_tk(ps, i, "function")
			return parse_function_args_rets_body(ps, i, node)
		end
```
This goes on for many more lines. My current thought as to why is that is is that at some point, `synID` or `synIDattr` seems to give up when it is sufficiently far enough away from the cursor, or it has sort of limit as the lines that it stops working aren't always the same. (Which gives me a thought, since some of the original code moved the cursor around while it was indenting, then reset it back to where it started. Perhaps this could be a solution?)

I may write a quick script to just generate simple but random teal code and just have it produce some random 10K line files to just test things out on.

In contrast, in my own sub 1K line projects that I have been translating to Teal, `gg=G` has been working fine.

**Comment by pdesaulniers** [comment]
Yeah, `tl.tl` is a pretty extreme test case. I'm pretty sure the great majority of Teal scripts won't encounter these issues.

**Comment by euclidianAce** [comment]
Small update: after some research and tinkering I came across [this issue](https://github.com/vim/vim/issues/1098). To summarize

- synID, synIDattr, and searchpair are notoriously slow.
- I am like 80% convinced that there is a timeout on these since bloating up the indent function causes the indent to fail earlier in tl.tl and trimming the indent function down makes it reach further
- One other thing I didn't consider when writing the syntax file is that look-behinds (the `\@=` stuff in the regexes) can also be slow.
  	- I did already know this, but for the case of syntax highlighting it wasn't so bad, now that indentation relies on it, it's not great.
- The good news is that look behind's search scope can be limited and hopefully cause a great increase in speed. Or even be eliminated entirely.

I'll do some tests locally and see if I can make any progress.

**Comment by euclidianAce** [comment]
Hey @pdesaulniers, I'm thinking of closing this as it's a pretty generic issue and opening up issues for some of the things discussed in here like it not working for large files, the
```
if (
...
) then
```
not being indented correctly and `ignorecase` affecting the indentation.

**Comment by pdesaulniers** [comment]
Sure, go ahead :+1:
